import { theme, getButtonStyles, getCardStyles, getInputStyles } from '../utils/theme';

export const loginStyles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.background,
    padding: '20px',
    fontFamily: theme.fonts.primary,
  },
  loginBox: {
    width: '100%',
    maxWidth: '420px',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    padding: '32px',
    boxShadow: theme.shadows.lg,
  },
  logo: {
    textAlign: 'center',
    marginBottom: '24px',
  },
  logoIcon: {
    width: '64px',
    height: '64px',
    backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.full,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 16px',
    color: '#fff',
    fontSize: '28px',
    fontWeight: 'bold',
  },
  title: {
    fontSize: '24px',
    fontWeight: '700',
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: '8px',
  },
  subtitle: {
    fontSize: '14px',
    color: theme.colors.textMuted,
    textAlign: 'center',
    marginBottom: '24px',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '500',
    color: theme.colors.text,
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    borderRadius: theme.borderRadius.md,
    border: `1px solid ${theme.colors.border}`,
    fontSize: '16px',
    backgroundColor: theme.colors.surface,
    outline: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    boxSizing: 'border-box',
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    borderRadius: theme.borderRadius.md,
    border: `1px solid ${theme.colors.border}`,
    fontSize: '16px',
    backgroundColor: theme.colors.surface,
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  button: {
    width: '100%',
    padding: '14px',
    borderRadius: theme.borderRadius.md,
    border: 'none',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backgroundColor: theme.colors.primary,
    color: '#ffffff',
    marginTop: '8px',
  },
  buttonSecondary: {
    width: '100%',
    padding: '14px',
    borderRadius: theme.borderRadius.md,
    border: `1px solid ${theme.colors.border}`,
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backgroundColor: theme.colors.surface,
    color: theme.colors.text,
    marginTop: '8px',
  },
  footer: {
    textAlign: 'center',
    marginTop: '20px',
    paddingTop: '20px',
    borderTop: `1px solid ${theme.colors.border}`,
  },
  footerLink: {
    color: theme.colors.primary,
    textDecoration: 'none',
    fontSize: '14px',
    cursor: 'pointer',
  },
  error: {
    backgroundColor: '#fef2f2',
    color: theme.colors.error,
    padding: '12px',
    borderRadius: theme.borderRadius.md,
    fontSize: '14px',
    marginBottom: '16px',
  },
  linkButtons: {
    display: 'flex',
    gap: '16px',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginTop: '16px',
  },
  linkButton: {
    background: 'transparent',
    border: 'none',
    fontSize: '13px',
    color: theme.colors.textMuted,
    cursor: 'pointer',
    padding: '8px',
  },
};

export const dashboardStyles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: theme.fonts.primary,
    backgroundColor: theme.colors.background,
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${theme.colors.border}`,
    flexWrap: 'wrap',
    gap: '12px',
  },
  title: {
    fontSize: '24px',
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: '4px',
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    border: `1px solid ${theme.colors.border}`,
    padding: '20px',
    marginBottom: '16px',
    boxShadow: theme.shadows.sm,
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: '16px',
  },
  button: {
    padding: '10px 20px',
    borderRadius: theme.borderRadius.md,
    border: 'none',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  buttonPrimary: {
    backgroundColor: theme.colors.primary,
    color: '#ffffff',
  },
  buttonSecondary: {
    backgroundColor: '#f1f5f9',
    color: theme.colors.text,
  },
  buttonDanger: {
    backgroundColor: theme.colors.error,
    color: '#ffffff',
  },
  badge: {
    display: 'inline-flex',
    padding: '4px 12px',
    borderRadius: theme.borderRadius.full,
    fontSize: '12px',
    fontWeight: '500',
  },
  badgeSuccess: {
    backgroundColor: '#dcfce7',
    color: theme.colors.success,
  },
  badgeWarning: {
    backgroundColor: '#fef3c7',
    color: theme.colors.warning,
  },
  badgeError: {
    backgroundColor: '#fee2e2',
    color: theme.colors.error,
  },
  badgePrimary: {
    backgroundColor: '#dbeafe',
    color: theme.colors.primary,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    textAlign: 'left',
    padding: '12px',
    borderBottom: `2px solid ${theme.colors.border}`,
    fontWeight: '600',
    color: theme.colors.textMuted,
    fontSize: '13px',
  },
  td: {
    padding: '12px',
    borderBottom: `1px solid ${theme.colors.border}`,
    fontSize: '14px',
  },
};

export default { loginStyles, dashboardStyles };